### ISSUE TITLE
Twitch IndexOutofBoundsException

### ISSUE THREAD

**Issue by Pwalne** [pircbotx/pircbotx#277] opened 2015-10-17 01:03 UTC
Connecting to twitch gives a OutOfBoundsException

JavaFX Application Thread] INFO org.pircbotx.PircBotX - Connected to server.
[JavaFX Application Thread] INFO org.pircbotx.output.OutputRaw - PASS oauth:xxxxxxxx
[JavaFX Application Thread] INFO org.pircbotx.output.OutputRaw - NICK poopsicle360
[JavaFX Application Thread] INFO org.pircbotx.output.OutputRaw - USER PircBotX 8 \* :PircBotX 2.0.1, a fork of PircBot, the Java IRC bot - pircbotx.googlecode.com
[JavaFX Application Thread] INFO org.pircbotx.InputParser - :tmi.twitch.tv 001 poopsicle360 :Welcome, GLHF!
[JavaFX Application Thread] INFO org.pircbotx.output.OutputRaw - JOIN #pyrostasis 
[JavaFX Application Thread] INFO org.pircbotx.InputParser - :tmi.twitch.tv 002 poopsicle360 :Your host is tmi.twitch.tv
[JavaFX Application Thread] INFO org.pircbotx.InputParser - :tmi.twitch.tv 003 poopsicle360 :This server is rather new
[JavaFX Application Thread] INFO org.pircbotx.InputParser - :tmi.twitch.tv 004 poopsicle360 :-
[JavaFX Application Thread] ERROR org.pircbotx.PircBotX - Exception encountered when parsing line
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at org.pircbotx.ServerInfo.parse004(ServerInfo.java:113)
    at org.pircbotx.ServerInfo.parse(ServerInfo.java:106)
    at org.pircbotx.InputParser.processServerResponse(InputParser.java:709)
    at org.pircbotx.InputParser.handleLine(InputParser.java:323)
    at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:275)
    at org.pircbotx.PircBotX.connect(PircBotX.java:236)
    at org.pircbotx.PircBotX.startBot(PircBotX.java:151)
    at irc.bot.IRCBot.start_bot(IRCBot.java:44)
    at irc.bot.IRCBot.run(IRCBot.java:64)
[JavaFX Application Thread] INFO org.pircbotx.InputParser - :tmi.twitch.tv 375 poopsicle360 :-
[JavaFX Application Thread] INFO org.pircbotx.InputParser - :tmi.twitch.tv 372 poopsicle360 :You are in a maze of twisty passages, all alike.
[JavaFX Application Thread] INFO org.pircbotx.InputParser - :tmi.twitch.tv 376 poopsicle360 :>

**Comment by TheLQ** [comment] 2015-10-26 23:15
Have you tried 2.1-SNAPSHOT? https://github.com/TheLQ/pircbotx/wiki/DevVersion

**Comment by TheLQ** [comment] 2015-11-10 01:07
Duplicate of Issue #234, was fixed a while ago in 2.1-SNAPSHOT

**Closed as completed** 2015-11-10 01:07 UTC
Labels: bug, duplicate
